spring:
  datasource:
    url : "jdbc:mysql://localhost:3307/DichoTienloi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username : root
    password : 1234
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform : org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "0W3qLeL6jzJngLVD3GO6zao26tDvm+CLerQOUoBxyOTSZZ+PypzVjDIct3fEKz4d"
  #valid-duration : 3600 # in seconds
  #refreshable-duration : 36000 #in seconds


server:
  port : 8082
  servlet:
    context-path: /ITSS_BE