spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql:3307/DichoTienloi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    password: ${DBMS_PASSWORD:1234}
    username: ${DBMS_USERNAME:root}
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform : org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "0W3qLeL6jzJngLVD3GO6zao26tDvm+CLerQOUoBxyOTSZZ+PypzVjDIct3fEKz4d"
  #valid-duration : 3600 # in seconds
  #refreshable-duration : 36000 #in seconds


server:
  port : 8080
  servlet:
    context-path: /ITSS_BE